BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
  cirrus_cli_pre_req_script:
    - chmod +x script/**/*
  arch_check_script:
    - uname -am
  test_script:
      - find . -name "*.sh" | xargs chmod +x
      - make install
      - make download_all_libs
      - make test
      - make grpc

PROTOC: &PROTOC
  protoc_script: |
    PROTOC_ZIP=protoc-3.14.0-linux-x86_64.zip
    curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/$PROTOC_ZIP
    unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
    unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
    rm -f $PROTOC_ZIP

linux_amd64_task:  
  env:
    matrix:
      - IMAGE: ruby:3.2
      - IMAGE: ruby:3.1
      - IMAGE: ruby:3.0
      - IMAGE: ruby:2.7
      - IMAGE: ruby:2.6
  container:
    image: $IMAGE
    architecture: amd64
  install_script: 
      - apt update --yes && apt install --yes jq protobuf-compiler
      - ruby --version
      - bundler --version
  << : *BUILD_TEST_TASK_TEMPLATE
  # << : *PROTOC

linux_arm64_task:  
  env:
    matrix:
      - IMAGE: ruby:3.2
      - IMAGE: ruby:3.1
      - IMAGE: ruby:3.0
      - IMAGE: ruby:2.7
      - IMAGE: ruby:2.6
  arm_container:
    image: $IMAGE
    architecture: arm64
  install_script: 
      - apt update --yes && apt install --yes jq protobuf-compiler
      - ruby --version
      - bundler --version
  <<: *BUILD_TEST_TASK_TEMPLATE
  # <<: *PROTOC

macos_arm64_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  env:
    PATH: ${HOME}/.pyenv/shims:${PATH}
    matrix:
      - IMAGE: 3.2.2 # preinstalled on macos-ventura-base
      # - IMAGE: 3.1.4
      # - IMAGE: 3.0.6
      - IMAGE: 2.7.8 # preinstalled on macos-ventura-base
      # - IMAGE: 2.6.10
  install_script:
    - brew install protobuf
    - rm /Users/admin/.rbenv/version
    - rbenv install ${IMAGE} || true
    - rbenv global ${IMAGE}
    - ruby --version
  << : *BUILD_TEST_TASK_TEMPLATE
