# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: area_calculator.proto for package 'area_calculator'

require 'grpc'
require 'area_calculator_pb'

module AreaCalculator
  module Calculator
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'area_calculator.Calculator'

      rpc :calculateOne, ::AreaCalculator::ShapeMessage, ::AreaCalculator::AreaResponse
      rpc :calculateMulti, ::AreaCalculator::AreaRequest, ::AreaCalculator::AreaResponse
    end

    Stub = Service.rpc_stub_class
  end
end
